version: '3.8'

services:
  weathermap:
    build: .
    image: weathermap:latest
    container_name: weathermap-server
    restart: unless-stopped
    ports:
      - "8112:8112"
    environment:
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8112/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - weathermap-network

networks:
  weathermap-network:
    driver: bridge