version: '3.8'

services:
  weathermap:
    build: .
    image: weathermap:production
    container_name: weathermap-prod
    restart: always
    ports:
      - "8112:8112"
    environment:
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8112/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - weathermap-network
    volumes:
      - weathermap-logs:/app/logs

  nginx:
    image: nginx:alpine
    container_name: weathermap-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
    depends_on:
      - weathermap
    networks:
      - weathermap-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  weathermap-network:
    driver: bridge

volumes:
  weathermap-logs:
    driver: local
  nginx-cache:
    driver: local